"""Generate a reuse remediation markdown report from scan results."""

from __future__ import annotations

from pathlib import Path

from dbt_governance.scanner import ReuseRecommendation, ScanResult


def _risk_label(high_priority_count: int, cluster_count: int, total_recommendations: int) -> str:
    if high_priority_count >= 3 or cluster_count >= 2:
        return "High"
    if high_priority_count >= 1 or total_recommendations >= 3:
        return "Moderate"
    return "Low"


def _render_feature_list(label: str, values: list[str]) -> list[str]:
    if not values:
        return []
    return [f"- {label}: {', '.join(values)}"]


def _render_recommendation(action: ReuseRecommendation, index: int) -> list[str]:
    lines = [
        f"### {index}. {action.recommendation_type.title()} Recommendation",
        "",
        f"- Priority: {action.priority}",
        f"- Confidence: {action.confidence_band}",
    ]

    if action.recommendation_type == "cluster":
        if action.cluster_average_score is not None:
            lines.append(f"- Average similarity: {action.cluster_average_score:.2f}")
        if action.cluster_peak_score is not None:
            lines.append(f"- Peak similarity: {action.cluster_peak_score:.2f}")
    elif action.similarity_score is not None:
        lines.append(f"- Similarity score: {action.similarity_score:.2f}")

    if action.model_names:
        lines.append(f"- Models: {', '.join(action.model_names)}")
    if action.suggested_shared_model:
        lines.append(f"- Suggested shared model: `{action.suggested_shared_model}`")

    lines.extend(["", action.summary])

    feature_lines = []
    feature_lines.extend(_render_feature_list("Shared inputs", action.shared_inputs))
    feature_lines.extend(_render_feature_list("Shared columns", action.shared_selected_columns))
    feature_lines.extend(_render_feature_list("Shared aggregates", action.shared_aggregates))
    feature_lines.extend(_render_feature_list("Shared filters", action.shared_filters))
    if feature_lines:
        lines.extend(["", "Signals:"])
        lines.extend(feature_lines)

    if action.example_pairs:
        lines.extend(["", "Example strong links:"])
        for pair in action.example_pairs:
            left = str(pair.get("left_model_name", ""))
            right = str(pair.get("right_model_name", ""))
            score = pair.get("similarity_score")
            if isinstance(score, (int, float)):
                lines.append(f"- `{left}` <-> `{right}` ({score:.2f})")
            else:
                lines.append(f"- `{left}` <-> `{right}`")

    return lines + [""]


def _render_executive_summary(result: ScanResult) -> list[str]:
    report = result.reuse_report
    if not report or report.total_recommendations == 0:
        return [
            "## Executive Summary",
            "",
            "No material re-use remediation work is currently prioritized from this scan.",
            "",
            "Governance recommendation: keep monitoring new migrations and review future scan results for emerging consolidation opportunities.",
            "",
        ]

    high_priority_actions = [action for action in report.prioritized_actions if action.priority == "high"]
    top_actions = report.prioritized_actions[:3]
    risk = _risk_label(len(high_priority_actions), report.cluster_count, report.total_recommendations)

    lines = [
        "## Executive Summary",
        "",
        f"- Re-use remediation risk: {risk}",
        f"- Highest-priority actions: {len(high_priority_actions)}",
        f"- Multi-model clusters to address: {report.cluster_count}",
        f"- Remaining pair consolidations: {report.remaining_pair_count}",
        "",
    ]

    if top_actions:
        lines.append("Recommended leadership focus:")
        for action in top_actions:
            focus_target = (
                f"{len(action.model_names)}-model cluster"
                if action.recommendation_type == "cluster"
                else f"{action.primary_model_name} + {action.paired_model_name}"
            )
            shared_model = action.suggested_shared_model or "a shared intermediate"
            lines.append(
                f"- {action.priority.title()} priority {action.recommendation_type}: consolidate {focus_target} into `{shared_model}`."
            )
        lines.append("")

    lines.append(
        "Governance recommendation: assign the top items first, starting with clusters because they usually remove the most duplicated migration logic in the least time."
    )
    lines.append("")
    return lines


def generate_reuse_md(result: ScanResult) -> str:
    """Render a reuse remediation report from a ScanResult."""
    lines = [
        "# Reuse Remediation Report",
        "",
        "<!-- Auto-generated by dbt-governance -->",
        "",
        f"Project: {result.project_name}",
        f"Generated at: {result.timestamp}",
        "",
    ]

    if not result.reuse_report or result.reuse_report.total_recommendations == 0:
        lines.extend(
            [
                *_render_executive_summary(result),
                "## Summary",
                "",
                "No ranked re-use recommendations were found in this scan.",
                "",
                "This means the scanner did not detect any high-confidence pairwise or cluster-level consolidation opportunities.",
                "",
            ]
        )
        return "\n".join(lines)

    report = result.reuse_report
    lines.extend(
        [
            *_render_executive_summary(result),
            "## Summary",
            "",
            f"- Total recommendations: {report.total_recommendations}",
            f"- Clusters: {report.cluster_count}",
            f"- Remaining pairs: {report.remaining_pair_count}",
            "",
            "Work the queue in order. Clusters are listed first because they usually remove the most migration redundancy in the least time.",
            "",
            "## Prioritized Actions",
            "",
        ]
    )

    for index, action in enumerate(report.prioritized_actions, start=1):
        lines.extend(_render_recommendation(action, index))

    if report.clusters:
        lines.extend(["## Cluster Recommendations", ""])
        for index, action in enumerate(report.clusters, start=1):
            lines.extend(_render_recommendation(action, index))

    if report.remaining_pairs:
        lines.extend(["## Remaining Pair Recommendations", ""])
        for index, action in enumerate(report.remaining_pairs, start=1):
            lines.extend(_render_recommendation(action, index))

    return "\n".join(lines)


def write_reuse_md(result: ScanResult, output_path: str | Path = "REUSE_REPORT.md") -> Path:
    """Write a reuse remediation report to disk and return the output path."""
    path = Path(output_path)
    path.write_text(generate_reuse_md(result), encoding="utf-8")
    return path
